module.exports = {
  realPlayersDB: [
  // GK
  { name: "Alisson Becker", position: "GK", baseOvr: 90 },
  { name: "Ederson", position: "GK", baseOvr: 89 },
  { name: "Thibaut Courtois", position: "GK", baseOvr: 90 },
  { name: "Marc-André ter Stegen", position: "GK", baseOvr: 89 },
  { name: "Jan Oblak", position: "GK", baseOvr: 88 },
  { name: "Gianluigi Donnarumma", position: "GK", baseOvr: 88 },
  { name: "Emiliano Martínez", position: "GK", baseOvr: 87 },
  { name: "Mike Maignan", position: "GK", baseOvr: 87 },
  { name: "Manuel Neuer", position: "GK", baseOvr: 87 },
  { name: "Yann Sommer", position: "GK", baseOvr: 85 },
  { name: "Guglielmo Vicario", position: "GK", baseOvr: 84 },
  { name: "Jordan Pickford", position: "GK", baseOvr: 84 },
  { name: "David Raya", position: "GK", baseOvr: 84 },
  { name: "André Onana", position: "GK", baseOvr: 83 },
  { name: "Alex Meret", position: "GK", baseOvr: 83 },
  { name: "Unai Simón", position: "GK", baseOvr: 84 },
  { name: "Gregor Kobel", position: "GK", baseOvr: 86 },
  { name: "Wojciech Szczęsny", position: "GK", baseOvr: 85 },
  { name: "Kepa Arrizabalaga", position: "GK", baseOvr: 82 },
  { name: "Aaron Ramsdale", position: "GK", baseOvr: 82 },
  { name: "Nick Pope", position: "GK", baseOvr: 82 },
  { name: "Lukasz Fabianski", position: "GK", baseOvr: 79 },
  { name: "Keylor Navas", position: "GK", baseOvr: 83 },
  { name: "Lev Yashin", position: "GK", baseOvr: 94 },
  { name: "Gianluigi Buffon", position: "GK", baseOvr: 93 },
  { name: "Iker Casillas", position: "GK", baseOvr: 92 },
  { name: "Peter Schmeichel", position: "GK", baseOvr: 91 },
  { name: "Essam El-Hadary", position: "GK", baseOvr: 87 },
  { name: "David de Gea", position: "GK", baseOvr: 85 },
  { name: "Hugo Lloris", position: "GK", baseOvr: 84 },
  { name: "Kasper Schmeichel", position: "GK", baseOvr: 83 },
  { name: "Stefan Ortega", position: "GK", baseOvr: 81 },
  { name: "Caoimhin Kelleher", position: "GK", baseOvr: 80 },
  { name: "Bernd Leno", position: "GK", baseOvr: 81 },
  { name: "Dida", position: "GK", baseOvr: 88 },
  { name: "Cláudio Taffarel", position: "GK", baseOvr: 87 },
  { name: "Oliver Kahn", position: "GK", baseOvr: 92 },
  { name: "Edwin van der Sar", position: "GK", baseOvr: 91 },
  { name: "Petr Čech", position: "GK", baseOvr: 91 },
  { name: "Julio César", position: "GK", baseOvr: 89 },
  // RB
  { name: "Kyle Walker", position: "RB", baseOvr: 85 },
  { name: "Trent Alexander-Arnold", position: "RB", baseOvr: 86 },
  { name: "Reece James", position: "RB", baseOvr: 84 },
  { name: "Kieran Trippier", position: "RB", baseOvr: 85 },
  { name: "Achraf Hakimi", position: "RB", baseOvr: 84 },
  { name: "Jeremie Frimpong", position: "RB", baseOvr: 84 },
  { name: "Dani Carvajal", position: "RB", baseOvr: 85 },
  { name: "Ben White", position: "RB", baseOvr: 83 },
  { name: "Diogo Dalot", position: "RB", baseOvr: 83 },
  { name: "Pedro Porro", position: "RB", baseOvr: 82 },
  { name: "Giovanni Di Lorenzo", position: "RB", baseOvr: 84 },
  { name: "Denzel Dumfries", position: "RB", baseOvr: 82 },
  { name: "Nahuel Molina", position: "RB", baseOvr: 82 },
  { name: "Joao Cancelo", position: "RB", baseOvr: 85 },
  { name: "Jules Koundé", position: "RB", baseOvr: 85 },
  { name: "Matty Cash", position: "RB", baseOvr: 79 },
  { name: "Aaron Wan-Bissaka", position: "RB", baseOvr: 80 },
  { name: "Malo Gusto", position: "RB", baseOvr: 80 },
  { name: "Takehiro Tomiyasu", position: "RB", baseOvr: 80 },
  { name: "Jonathan Clauss", position: "RB", baseOvr: 81 },
  { name: "Nordi Mukiele", position: "RB", baseOvr: 79 },
  { name: "Sergi Roberto", position: "RB", baseOvr: 80 },
  { name: "Jesus Navas", position: "RB", baseOvr: 80 },
  { name: "Cafu", position: "RB", baseOvr: 93 },
  { name: "Philipp Lahm", position: "RB", baseOvr: 92 },
  { name: "Javier Zanetti", position: "RB", baseOvr: 92 },
  { name: "Carlos Alberto", position: "RB", baseOvr: 91 },
  { name: "Ahmed Fathy", position: "RB", baseOvr: 85 },
  { name: "Lilian Thuram", position: "RB", baseOvr: 88 },
  { name: "Branislav Ivanović", position: "RB", baseOvr: 84 },
  { name: "Micah Richards", position: "RB", baseOvr: 81 },
  { name: "Pablo Zabaleta", position: "RB", baseOvr: 83 },
  { name: "Maicon", position: "RB", baseOvr: 89 },
  { name: "Gary Neville", position: "RB", baseOvr: 87 },
  { name: "Noussair Mazraoui", position: "RB", baseOvr: 81 },
  { name: "Sergiño Dest", position: "RB", baseOvr: 78 },
  { name: "Hector Bellerin", position: "RB", baseOvr: 79 },
  { name: "Tariq Lamptey", position: "RB", baseOvr: 77 },
  { name: "Seamus Coleman", position: "RB", baseOvr: 79 },
  { name: "Nathaniel Clyne", position: "RB", baseOvr: 78 },
  // LB
  { name: "Andrew Robertson", position: "LB", baseOvr: 86 },
  { name: "Theo Hernández", position: "LB", baseOvr: 85 },
  { name: "Alphonso Davies", position: "LB", baseOvr: 84 },
  { name: "Ferland Mendy", position: "LB", baseOvr: 83 },
  { name: "Oleksandr Zinchenko", position: "LB", baseOvr: 83 },
  { name: "Luke Shaw", position: "LB", baseOvr: 82 },
  { name: "Destiny Udogie", position: "LB", baseOvr: 81 },
  { name: "Federico Dimarco", position: "LB", baseOvr: 84 },
  { name: "Alejandro Grimaldo", position: "LB", baseOvr: 84 },
  { name: "Nuno Mendes", position: "LB", baseOvr: 82 },
  { name: "Ben Chilwell", position: "LB", baseOvr: 80 },
  { name: "Pervis Estupiñán", position: "LB", baseOvr: 80 },
  { name: "Marcos Acuña", position: "LB", baseOvr: 82 },
  { name: "José Gayà", position: "LB", baseOvr: 81 },
  { name: "Ian Maatsen", position: "LB", baseOvr: 79 },
  { name: "Antonee Robinson", position: "LB", baseOvr: 79 },
  { name: "Raphaël Guerreiro", position: "LB", baseOvr: 81 },
  { name: "David Raum", position: "LB", baseOvr: 80 },
  { name: "Tyrick Mitchell", position: "LB", baseOvr: 78 },
  { name: "Rico Henry", position: "LB", baseOvr: 78 },
  { name: "Emerson Palmieri", position: "LB", baseOvr: 79 },
  { name: "Lucas Digne", position: "LB", baseOvr: 79 },
  { name: "Rayan Aït-Nouri", position: "LB", baseOvr: 79 },
  { name: "Roberto Carlos", position: "LB", baseOvr: 92 },
  { name: "Paolo Maldini", position: "LB", baseOvr: 94 },
  { name: "Ashley Cole", position: "LB", baseOvr: 89 },
  { name: "Marcelo", position: "LB", baseOvr: 88 },
  { name: "Sayed Moawad", position: "LB", baseOvr: 85 },
  { name: "Kieran Tierney", position: "LB", baseOvr: 80 },
  { name: "Jordi Alba", position: "LB", baseOvr: 84 },
  { name: "Alex Sandro", position: "LB", baseOvr: 81 },
  { name: "Alex Telles", position: "LB", baseOvr: 80 },
  { name: "Renan Lodi", position: "LB", baseOvr: 79 },
  { name: "Bixente Lizarazu", position: "LB", baseOvr: 87 },
  { name: "Denis Irwin", position: "LB", baseOvr: 85 },
  { name: "Patrice Evra", position: "LB", baseOvr: 88 },
  { name: "Joan Capdevila", position: "LB", baseOvr: 86 },
  { name: "Fabio Grosso", position: "LB", baseOvr: 84 },
  { name: "Gael Clichy", position: "LB", baseOvr: 81 },
  { name: "Leighton Baines", position: "LB", baseOvr: 83 },
  // CB
  { name: "Virgil van Dijk", position: "CB", baseOvr: 90 },
  { name: "Rúben Dias", position: "CB", baseOvr: 89 },
  { name: "William Saliba", position: "CB", baseOvr: 87 },
  { name: "John Stones", position: "CB", baseOvr: 86 },
  { name: "Antonio Rüdiger", position: "CB", baseOvr: 86 },
  { name: "Marquinhos", position: "CB", baseOvr: 86 },
  { name: "Ronald Araújo", position: "CB", baseOvr: 85 },
  { name: "Éder Militão", position: "CB", baseOvr: 85 },
  { name: "Alessandro Bastoni", position: "CB", baseOvr: 85 },
  { name: "Kim Min Jae", position: "CB", baseOvr: 84 },
  { name: "Gabriel Magalhães", position: "CB", baseOvr: 84 },
  { name: "Sven Botman", position: "CB", baseOvr: 83 },
  { name: "Lisandro Martínez", position: "CB", baseOvr: 83 },
  { name: "Cristian Romero", position: "CB", baseOvr: 83 },
  { name: "Dayot Upamecano", position: "CB", baseOvr: 83 },
  { name: "Ibrahima Konaté", position: "CB", baseOvr: 82 },
  { name: "Manuel Akanji", position: "CB", baseOvr: 82 },
  { name: "Raphaël Varane", position: "CB", baseOvr: 84 },
  { name: "Thiago Silva", position: "CB", baseOvr: 83 },
  { name: "Bremer", position: "CB", baseOvr: 84 },
  { name: "Fikayo Tomori", position: "CB", baseOvr: 83 },
  { name: "Pau Torres", position: "CB", baseOvr: 82 },
  { name: "Nathan Aké", position: "CB", baseOvr: 82 },
  { name: "Franco Baresi", position: "CB", baseOvr: 93 },
  { name: "Franz Beckenbauer", position: "CB", baseOvr: 94 },
  { name: "Sergio Ramos", position: "CB", baseOvr: 91 },
  { name: "Fabio Cannavaro", position: "CB", baseOvr: 92 },
  { name: "Wael Gomaa", position: "CB", baseOvr: 86 },
  { name: "Alessandro Nesta", position: "CB", baseOvr: 92 },
  { name: "Carles Puyol", position: "CB", baseOvr: 91 },
  { name: "John Terry", position: "CB", baseOvr: 90 },
  { name: "Rio Ferdinand", position: "CB", baseOvr: 90 },
  { name: "Nemanja Vidić", position: "CB", baseOvr: 89 },
  { name: "Vincent Kompany", position: "CB", baseOvr: 89 },
  { name: "Jaap Stam", position: "CB", baseOvr: 89 },
  { name: "Gerard Piqué", position: "CB", baseOvr: 88 },
  { name: "Giorgio Chiellini", position: "CB", baseOvr: 88 },
  { name: "Pepe", position: "CB", baseOvr: 87 },
  { name: "Diego Godín", position: "CB", baseOvr: 87 },
  { name: "Mats Hummels", position: "CB", baseOvr: 87 },
  // CDM
  { name: "Rodri", position: "CDM", baseOvr: 90 },
  { name: "Declan Rice", position: "CDM", baseOvr: 87 },
  { name: "Casemiro", position: "CDM", baseOvr: 87 },
  { name: "Joshua Kimmich", position: "CDM", baseOvr: 87 },
  { name: "N'Golo Kanté", position: "CDM", baseOvr: 86 },
  { name: "Sandro Tonali", position: "CDM", baseOvr: 85 },
  { name: "Aurélien Tchouaméni", position: "CDM", baseOvr: 85 },
  { name: "Bruno Guimarães", position: "CDM", baseOvr: 85 },
  { name: "Thomas Partey", position: "CDM", baseOvr: 84 },
  { name: "João Palhinha", position: "CDM", baseOvr: 84 },
  { name: "Edson Álvarez", position: "CDM", baseOvr: 82 },
  { name: "Moisés Caicedo", position: "CDM", baseOvr: 82 },
  { name: "Yves Bissouma", position: "CDM", baseOvr: 82 },
  { name: "Douglas Luiz", position: "CDM", baseOvr: 83 },
  { name: "Boubacar Kamara", position: "CDM", baseOvr: 81 },
  { name: "Manuel Ugarte", position: "CDM", baseOvr: 81 },
  { name: "Amadou Onana", position: "CDM", baseOvr: 80 },
  { name: "Sofyan Amrabat", position: "CDM", baseOvr: 80 },
  { name: "Pierre-Emile Højbjerg", position: "CDM", baseOvr: 80 },
  { name: "Wataru Endo", position: "CDM", baseOvr: 80 },
  { name: "Cheick Doucouré", position: "CDM", baseOvr: 79 },
  { name: "Tyler Adams", position: "CDM", baseOvr: 79 },
  { name: "Kalvin Phillips", position: "CDM", baseOvr: 78 },
  { name: "Claude Makélélé", position: "CDM", baseOvr: 90 },
  { name: "Patrick Vieira", position: "CDM", baseOvr: 91 },
  { name: "Roy Keane", position: "CDM", baseOvr: 90 },
  { name: "Gennaro Gattuso", position: "CDM", baseOvr: 89 },
  { name: "Hossam Ashour", position: "CDM", baseOvr: 85 },
  { name: "Sergio Busquets", position: "CDM", baseOvr: 88 },
  { name: "Xabi Alonso", position: "CDM", baseOvr: 88 },
  { name: "Andrea Pirlo", position: "CDM", baseOvr: 90 },
  { name: "Lothar Matthäus", position: "CDM", baseOvr: 93 },
  { name: "Frank Rijkaard", position: "CDM", baseOvr: 90 },
  { name: "Michael Essien", position: "CDM", baseOvr: 88 },
  { name: "Esteban Cambiasso", position: "CDM", baseOvr: 87 },
  { name: "Javier Mascherano", position: "CDM", baseOvr: 87 },
  { name: "Daniele De Rossi", position: "CDM", baseOvr: 86 },
  { name: "Gilberto Silva", position: "CDM", baseOvr: 85 },
  { name: "Edgar Davids", position: "CDM", baseOvr: 86 },
  { name: "Fernandinho", position: "CDM", baseOvr: 86 },
  // CM
  { name: "Kevin De Bruyne", position: "CM", baseOvr: 91 },
  { name: "Luka Modrić", position: "CM", baseOvr: 88 },
  { name: "Frenkie de Jong", position: "CM", baseOvr: 87 },
  { name: "Toni Kroos", position: "CM", baseOvr: 87 },
  { name: "Nicolò Barella", position: "CM", baseOvr: 86 },
  { name: "Jude Bellingham", position: "CM", baseOvr: 88 },
  { name: "Federico Valverde", position: "CM", baseOvr: 87 },
  { name: "Bernardo Silva", position: "CM", baseOvr: 88 },
  { name: "Martin Ødegaard", position: "CM", baseOvr: 87 },
  { name: "İlkay Gündoğan", position: "CM", baseOvr: 86 },
  { name: "Pedri", position: "CM", baseOvr: 86 },
  { name: "Gavi", position: "CM", baseOvr: 84 },
  { name: "Enzo Fernández", position: "CM", baseOvr: 83 },
  { name: "Mac Allister", position: "CM", baseOvr: 84 },
  { name: "Leon Goretzka", position: "CM", baseOvr: 85 },
  { name: "Eduardo Camavinga", position: "CM", baseOvr: 83 },
  { name: "Mateo Kovačić", position: "CM", baseOvr: 83 },
  { name: "Christian Eriksen", position: "CM", baseOvr: 82 },
  { name: "Youri Tielemans", position: "CM", baseOvr: 81 },
  { name: "Granit Xhaka", position: "CM", baseOvr: 83 },
  { name: "Rodrigo Bentancur", position: "CM", baseOvr: 82 },
  { name: "John McGinn", position: "CM", baseOvr: 81 },
  { name: "Conor Gallagher", position: "CM", baseOvr: 80 },
  { name: "Zinedine Zidane", position: "CM", baseOvr: 96 },
  { name: "Andrés Iniesta", position: "CM", baseOvr: 93 },
  { name: "Xavi", position: "CM", baseOvr: 93 },
  { name: "Steven Gerrard", position: "CM", baseOvr: 91 },
  { name: "Mohamed Shawky", position: "CM", baseOvr: 85 },
  { name: "Frank Lampard", position: "CM", baseOvr: 90 },
  { name: "Paul Scholes", position: "CM", baseOvr: 89 },
  { name: "Cesc Fàbregas", position: "CM", baseOvr: 88 },
  { name: "Bastian Schweinsteiger", position: "CM", baseOvr: 88 },
  { name: "Clarence Seedorf", position: "CM", baseOvr: 89 },
  { name: "Ruud Gullit", position: "CM", baseOvr: 93 },
  { name: "Michael Ballack", position: "CM", baseOvr: 89 },
  { name: "Deco", position: "CM", baseOvr: 88 },
  { name: "Arturo Vidal", position: "CM", baseOvr: 86 },
  { name: "Ivan Rakitić", position: "CM", baseOvr: 85 },
  { name: "Paul Pogba", position: "CM", baseOvr: 86 },
  { name: "Thiago Alcântara", position: "CM", baseOvr: 85 },
  // CAM
  { name: "Bruno Fernandes", position: "CAM", baseOvr: 88 },
  { name: "Jamal Musiala", position: "CAM", baseOvr: 87 },
  { name: "Florian Wirtz", position: "CAM", baseOvr: 86 },
  { name: "Christopher Nkunku", position: "CAM", baseOvr: 85 },
  { name: "Phil Foden", position: "CAM", baseOvr: 86 },
  { name: "James Maddison", position: "CAM", baseOvr: 84 },
  { name: "Mason Mount", position: "CAM", baseOvr: 81 },
  { name: "Dominik Szoboszlai", position: "CAM", baseOvr: 83 },
  { name: "Lucas Paquetá", position: "CAM", baseOvr: 82 },
  { name: "Eberechi Eze", position: "CAM", baseOvr: 81 },
  { name: "Piotr Zieliński", position: "CAM", baseOvr: 83 },
  { name: "Lorenzo Pellegrini", position: "CAM", baseOvr: 83 },
  { name: "Julian Brandt", position: "CAM", baseOvr: 83 },
  { name: "Dani Olmo", position: "CAM", baseOvr: 83 },
  { name: "Nabil Fekir", position: "CAM", baseOvr: 82 },
  { name: "Brahim Díaz", position: "CAM", baseOvr: 81 },
  { name: "Xavi Simons", position: "CAM", baseOvr: 81 },
  { name: "Morgan Gibbs-White", position: "CAM", baseOvr: 79 },
  { name: "Emile Smith Rowe", position: "CAM", baseOvr: 78 },
  { name: "Andreas Pereira", position: "CAM", baseOvr: 78 },
  { name: "Daichi Kamada", position: "CAM", baseOvr: 79 },
  { name: "Hakan Çalhanoğlu", position: "CAM", baseOvr: 85 },
  { name: "Paulo Dybala", position: "CAM", baseOvr: 86 },
  { name: "Diego Maradona", position: "CAM", baseOvr: 97 },
  { name: "Ronaldinho", position: "CAM", baseOvr: 94 },
  { name: "Kaká", position: "CAM", baseOvr: 92 },
  { name: "Juan Román Riquelme", position: "CAM", baseOvr: 89 },
  { name: "Mohamed Aboutrika", position: "CAM", baseOvr: 89 },
  { name: "Wesley Sneijder", position: "CAM", baseOvr: 89 },
  { name: "Mesut Özil", position: "CAM", baseOvr: 88 },
  { name: "David Silva", position: "CAM", baseOvr: 88 },
  { name: "Juan Mata", position: "CAM", baseOvr: 85 },
  { name: "Rui Costa", position: "CAM", baseOvr: 88 },
  { name: "Zico", position: "CAM", baseOvr: 93 },
  { name: "Michel Platini", position: "CAM", baseOvr: 94 },
  { name: "Michael Laudrup", position: "CAM", baseOvr: 90 },
  { name: "Gheorghe Hagi", position: "CAM", baseOvr: 89 },
  { name: "Jay-Jay Okocha", position: "CAM", baseOvr: 87 },
  { name: "Thomas Müller", position: "CAM", baseOvr: 87 },
  { name: "James Rodríguez", position: "CAM", baseOvr: 85 },
  // RW
  { name: "Mohamed Salah", position: "RW", baseOvr: 90 },
  { name: "Bukayo Saka", position: "RW", baseOvr: 87 },
  { name: "Rodrygo", position: "RW", baseOvr: 86 },
  { name: "Ousmane Dembélé", position: "RW", baseOvr: 85 },
  { name: "Riyad Mahrez", position: "RW", baseOvr: 85 },
  { name: "Lionel Messi", position: "RW", baseOvr: 90 },
  { name: "Leroy Sané", position: "RW", baseOvr: 85 },
  { name: "Dejan Kulusevski", position: "RW", baseOvr: 82 },
  { name: "Antony", position: "RW", baseOvr: 80 },
  { name: "Raphinha", position: "RW", baseOvr: 84 },
  { name: "Moussa Diaby", position: "RW", baseOvr: 83 },
  { name: "Jarrod Bowen", position: "RW", baseOvr: 82 },
  { name: "Michael Olise", position: "RW", baseOvr: 81 },
  { name: "Pedro Neto", position: "RW", baseOvr: 80 },
  { name: "Serge Gnabry", position: "RW", baseOvr: 83 },
  { name: "Marco Asensio", position: "RW", baseOvr: 82 },
  { name: "Federico Chiesa", position: "RW", baseOvr: 83 },
  { name: "Leon Bailey", position: "RW", baseOvr: 80 },
  { name: "Miguel Almirón", position: "RW", baseOvr: 80 },
  { name: "Bryan Mbeumo", position: "RW", baseOvr: 79 },
  { name: "Brennan Johnson", position: "RW", baseOvr: 78 },
  { name: "Christian Pulisic", position: "RW", baseOvr: 80 },
  { name: "Domenico Berardi", position: "RW", baseOvr: 84 },
  { name: "Garrincha", position: "RW", baseOvr: 94 },
  { name: "Luis Figo", position: "RW", baseOvr: 91 },
  { name: "George Best", position: "RW", baseOvr: 93 },
  { name: "Arjen Robben", position: "RW", baseOvr: 90 },
  { name: "Mohamed Barakat", position: "RW", baseOvr: 86 },
  { name: "Angel Di Maria", position: "RW", baseOvr: 86 },
  { name: "Gareth Bale", position: "RW", baseOvr: 89 },
  { name: "Jairzinho", position: "RW", baseOvr: 92 },
  { name: "Joe Cole", position: "RW", baseOvr: 85 },
  { name: "Freddie Ljungberg", position: "RW", baseOvr: 86 },
  { name: "Pavel Nedvěd", position: "RW", baseOvr: 89 },
  { name: "Eden Hazard", position: "RW", baseOvr: 89 },
  { name: "Raheem Sterling", position: "RW", baseOvr: 84 },
  { name: "Hulk", position: "RW", baseOvr: 83 },
  { name: "Willian", position: "RW", baseOvr: 82 },
  { name: "Xherdan Shaqiri", position: "RW", baseOvr: 81 },
  { name: "Adama Traoré", position: "RW", baseOvr: 79 },
  // LW
  { name: "Kylian Mbappé", position: "LW", baseOvr: 91 },
  { name: "Vinícius Júnior", position: "LW", baseOvr: 89 },
  { name: "Son Heung-min", position: "LW", baseOvr: 88 },
  { name: "Rafael Leão", position: "LW", baseOvr: 87 },
  { name: "Khvicha Kvaratskhelia", position: "LW", baseOvr: 86 },
  { name: "Gabriel Martinelli", position: "LW", baseOvr: 84 },
  { name: "Jack Grealish", position: "LW", baseOvr: 84 },
  { name: "Marcus Rashford", position: "LW", baseOvr: 84 },
  { name: "Luis Díaz", position: "LW", baseOvr: 84 },
  { name: "Jérémy Doku", position: "LW", baseOvr: 81 },
  { name: "Kaoru Mitoma", position: "LW", baseOvr: 81 },
  { name: "Anthony Gordon", position: "LW", baseOvr: 80 },
  { name: "Alejandro Garnacho", position: "LW", baseOvr: 79 },
  { name: "Mykhailo Mudryk", position: "LW", baseOvr: 78 },
  { name: "Harvey Barnes", position: "LW", baseOvr: 79 },
  { name: "Raheem Sterling", position: "LW", baseOvr: 82 },
  { name: "Cody Gakpo", position: "LW", baseOvr: 82 },
  { name: "Kingsley Coman", position: "LW", baseOvr: 85 },
  { name: "Karim Adeyemi", position: "LW", baseOvr: 80 },
  { name: "Neymar Jr", position: "LW", baseOvr: 88 },
  { name: "Ferran Torres", position: "LW", baseOvr: 81 },
  { name: "Leandro Trossard", position: "LW", baseOvr: 81 },
  { name: "Galeno", position: "LW", baseOvr: 80 },
  { name: "Thierry Henry", position: "LW", baseOvr: 93 },
  { name: "Ronaldinho", position: "LW", baseOvr: 94 },
  { name: "Hristo Stoichkov", position: "LW", baseOvr: 90 },
  { name: "Ryan Giggs", position: "LW", baseOvr: 89 },
  { name: "Mahmoud El Khatib", position: "LW", baseOvr: 88 },
  { name: "Sadio Mané", position: "LW", baseOvr: 87 },
  { name: "David Ginola", position: "LW", baseOvr: 88 },
  { name: "Marc Overmars", position: "LW", baseOvr: 87 },
  { name: "John Barnes", position: "LW", baseOvr: 87 },
  { name: "Harry Kewell", position: "LW", baseOvr: 85 },
  { name: "Marco Reus", position: "LW", baseOvr: 86 },
  { name: "Pedro", position: "LW", baseOvr: 84 },
  { name: "David Villa", position: "LW", baseOvr: 88 },
  { name: "Alexis Sánchez", position: "LW", baseOvr: 85 },
  { name: "Dimitri Payet", position: "LW", baseOvr: 83 },
  { name: "Franck Ribéry", position: "LW", baseOvr: 89 },
  { name: "Robert Pires", position: "LW", baseOvr: 88 },
  // ST
  { name: "Erling Haaland", position: "ST", baseOvr: 91 },
  { name: "Harry Kane", position: "ST", baseOvr: 90 },
  { name: "Robert Lewandowski", position: "ST", baseOvr: 90 },
  { name: "Victor Osimhen", position: "ST", baseOvr: 88 },
  { name: "Karim Benzema", position: "ST", baseOvr: 89 },
  { name: "Lautaro Martínez", position: "ST", baseOvr: 87 },
  { name: "Antoine Griezmann", position: "ST", baseOvr: 88 },
  { name: "Alexander Isak", position: "ST", baseOvr: 83 },
  { name: "Ollie Watkins", position: "ST", baseOvr: 83 },
  { name: "Ivan Toney", position: "ST", baseOvr: 82 },
  { name: "Julian Álvarez", position: "ST", baseOvr: 83 },
  { name: "Darwin Núñez", position: "ST", baseOvr: 82 },
  { name: "Callum Wilson", position: "ST", baseOvr: 81 },
  { name: "Gabriel Jesus", position: "ST", baseOvr: 83 },
  { name: "Rasmus Højlund", position: "ST", baseOvr: 79 },
  { name: "Dusan Vlahovic", position: "ST", baseOvr: 84 },
  { name: "Romelu Lukaku", position: "ST", baseOvr: 83 },
  { name: "Ciro Immobile", position: "ST", baseOvr: 84 },
  { name: "Randal Kolo Muani", position: "ST", baseOvr: 83 },
  { name: "Marcus Thuram", position: "ST", baseOvr: 81 },
  { name: "Gonçalo Ramos", position: "ST", baseOvr: 80 },
  { name: "Dominic Solanke", position: "ST", baseOvr: 79 },
  { name: "Richarlison", position: "ST", baseOvr: 80 },
  { name: "Pelé", position: "ST", baseOvr: 98 },
  { name: "Ronaldo Nazário", position: "ST", baseOvr: 97 },
  { name: "Marco van Basten", position: "ST", baseOvr: 93 },
  { name: "Romário", position: "ST", baseOvr: 92 },
  { name: "Emad Moteab", position: "ST", baseOvr: 86 },
  { name: "Wayne Rooney", position: "ST", baseOvr: 90 },
  { name: "Sergio Agüero", position: "ST", baseOvr: 89 },
  { name: "Luis Suárez", position: "ST", baseOvr: 90 },
  { name: "Zlatan Ibrahimović", position: "ST", baseOvr: 90 },
  { name: "Didier Drogba", position: "ST", baseOvr: 89 },
  { name: "Samuel Eto'o", position: "ST", baseOvr: 90 },
  { name: "Alan Shearer", position: "ST", baseOvr: 90 },
  { name: "Ian Wright", position: "ST", baseOvr: 88 },
  { name: "Fernando Torres", position: "ST", baseOvr: 88 },
  { name: "Ruud van Nistelrooy", position: "ST", baseOvr: 90 },
  { name: "Robin van Persie", position: "ST", baseOvr: 89 },
  { name: "Dennis Bergkamp", position: "ST", baseOvr: 90 },
  // Manager
  { name: "Pep Guardiola", position: "Manager", baseOvr: 93 },
  { name: "Jürgen Klopp", position: "Manager", baseOvr: 92 },
  { name: "Carlo Ancelotti", position: "Manager", baseOvr: 91 },
  { name: "Mikel Arteta", position: "Manager", baseOvr: 89 },
  { name: "Xabi Alonso", position: "Manager", baseOvr: 88 },
  { name: "Diego Simeone", position: "Manager", baseOvr: 89 },
  { name: "Antonio Conte", position: "Manager", baseOvr: 87 },
  { name: "Thomas Tuchel", position: "Manager", baseOvr: 86 },
  { name: "Unai Emery", position: "Manager", baseOvr: 86 },
  { name: "Ange Postecoglou", position: "Manager", baseOvr: 85 },
  { name: "Roberto De Zerbi", position: "Manager", baseOvr: 84 },
  { name: "Eddie Howe", position: "Manager", baseOvr: 83 },
  { name: "Sir Alex Ferguson", position: "Manager", baseOvr: 96 },
  { name: "Hassan Shehata", position: "Manager", baseOvr: 88 },
  { name: "Arsène Wenger", position: "Manager", baseOvr: 92 },
  { name: "Jose Mourinho", position: "Manager", baseOvr: 92 },
  { name: "Zinedine Zidane", position: "Manager", baseOvr: 90 },
  { name: "Massimiliano Allegri", position: "Manager", baseOvr: 88 },
  { name: "Mauricio Pochettino", position: "Manager", baseOvr: 86 },
  { name: "Gareth Southgate", position: "Manager", baseOvr: 83 },
  // NEW HIGH-PROFILE PLAYERS 
  { name: "Kylian Mbappé", position: "ST", baseOvr: 91 },
  { name: "Erling Haaland", position: "ST", baseOvr: 91 },
  { name: "Vinícius Jr.", position: "LW", baseOvr: 91 },
  { name: "Jude Bellingham", position: "CM", baseOvr: 91 },
  { name: "Mohamed Salah", position: "RW", baseOvr: 89 },
  { name: "Lionel Messi", position: "RW", baseOvr: 88 },
  { name: "Cristiano Ronaldo", position: "ST", baseOvr: 86 },
  { name: "Kevin De Bruyne", position: "CM", baseOvr: 90 },
  { name: "Virgil van Dijk", position: "CB", baseOvr: 89 },
  { name: "Phil Foden", position: "RW", baseOvr: 89 },
  { name: "Bukayo Saka", position: "RW", baseOvr: 88 },
  { name: "Lamine Yamal", position: "RW", baseOvr: 87 },
  { name: "Rodri", position: "CM", baseOvr: 91 },
  { name: "Declan Rice", position: "CM", baseOvr: 88 },
  { name: "Martin Ødegaard", position: "CAM", baseOvr: 89 },
  { name: "Harry Kane", position: "ST", baseOvr: 90 },
  { name: "Robert Lewandowski", position: "ST", baseOvr: 88 },
  { name: "Jamal Musiala", position: "CAM", baseOvr: 89 },
  { name: "Florian Wirtz", position: "CAM", baseOvr: 89 },
  { name: "Toni Kroos", position: "CM", baseOvr: 90 },
  { name: "Luka Modrić", position: "CM", baseOvr: 86 },
  { name: "Antoine Griezmann", position: "ST", baseOvr: 88 },
  { name: "Heung Min Son", position: "LW", baseOvr: 88 },
  { name: "Rafael Leão", position: "LW", baseOvr: 87 },
  { name: "Victor Osimhen", position: "ST", baseOvr: 87 },
  { name: "Federico Valverde", position: "CM", baseOvr: 89 },
  { name: "Aurélien Tchouaméni", position: "CM", baseOvr: 87 },
  { name: "Eduardo Camavinga", position: "CM", baseOvr: 86 },
  { name: "Rúben Dias", position: "CB", baseOvr: 89 },
  { name: "William Saliba", position: "CB", baseOvr: 88 },
  { name: "Antonio Rüdiger", position: "CB", baseOvr: 88 },
  { name: "Marquinhos", position: "CB", baseOvr: 87 },
  { name: "Ronald Araujo", position: "CB", baseOvr: 86 },
  { name: "Alessandro Bastoni", position: "CB", baseOvr: 87 },
  { name: "Josko Gvardiol", position: "LB", baseOvr: 86 },
  { name: "Bruno Fernandes", position: "CAM", baseOvr: 88 },
  { name: "Bernardo Silva", position: "CAM", baseOvr: 88 },
  { name: "Neymar Jr", position: "LW", baseOvr: 86 },
  { name: "Ousmane Dembélé", position: "RW", baseOvr: 86 },
  { name: "Khvicha Kvaratskhelia", position: "LW", baseOvr: 87 },
  { name: "Lautaro Martínez", position: "ST", baseOvr: 88 },
  { name: "Xavi Simons", position: "CAM", baseOvr: 86 },
  { name: "Pedri", position: "CM", baseOvr: 87 },
  { name: "Gavi", position: "CM", baseOvr: 86 },
  { name: "Frenkie de Jong", position: "CM", baseOvr: 87 },
  { name: "Nicolo Barella", position: "CM", baseOvr: 88 },
  { name: "Cole Palmer", position: "CAM", baseOvr: 88 },
  { name: "Endrick", position: "ST", baseOvr: 83 }
  ]
};
